name: Clean Project Cache

on:
  workflow_dispatch:

jobs:
  clean_cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.os }}-${{ hashFiles('Cargo.toml') }}
      - uses: actions-rs/cargo@v1
        with:
          command: clean
